### PR TITLE
Implement `get` and `serve` commands

### LINKED ISSUE #15: Implement `get` command with human-readable tabular output
The `get` command fetches rows from tables in the Nanobot database. It will eventually support PostgREST-style filtering and multiple output formats. Some of this functionality might be better in `valve.rs`, but we will prototype it here. I created a `get-command` branch with a [`doc/get.md`](https://github.com/ontodev/nanobot.rs/blob/get-command/doc/get.md) file, including `tesh` tests.

I think we'll want to add a dependency on `sqlx`, and we should look to `valve.rs` for examples. For now we only need SQLite support. I think I also want to use <https://github.com/BurntSushi/tabwriter>. Next we'll add JSON support, for which we'll want `serde` and `serde-json` -- we can add them now if that's easier.

To get the output in `doc/get.md` we'll need to run a simple SQL query like `SELECT * FROM "table_view" LIMIT 100`. We'll ignore the 'row_number' column for now, and eventually add an option for including it. Eventually we'll want to generate fancy queries dynamically, but I'm fine with a string substitution for now.

### LINKED ISSUE #16: Add basic JSON support to `get`
Building on #15, we need JSON output that matches [PostgREST](https://postgrest.org/). The [`doc/get.md`](https://github.com/ontodev/nanobot.rs/blob/get-command/doc/get.md) already includes an example. The SQL query would be the same as #15 but we need to convert it to simple JSON. Keys will all be strings. Most values will be strings, with the exception (for now) of 'row_number'.

### PR DESCRIPTION
**Pull request by jamesaoverton**
Merged #17 by hand to close #15 and close #16.

Also implement a first pass at a `nanobot serve` command, that will run an HTTP server.

- [X] use `axum` as an HTTP server
- [X] use `minijinja` for templating HTML
- [X] read templates and example JSON from `src/resources/`
- [x] read from SQLite
- [x] handle query parameters, PostgREST basics

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This should use `get` from #17 but currently I just hack that part together.

**Comment by jamesaoverton** [comment]
I think this is ready to merge. @ckindermann please review it. I'll continue my work on another branch.

**Comment by ckindermann** [comment]
`nanobot get` has two (non-required) options:

1. `shape` and
2. `format`.

We are currently using [default values](https://github.com/ontodev/nanobot.rs/blob/serve/src/main.rs#L74) for both:

1. `shape` is set to `value_rows` and
2. `format` is set to `text`.

However, the options cannot be combined in arbitrary ways. For example `nanobot get table -s page -f text` yields `ERROR: GetError { details: "Shape 'page' does not support format 'text'" }`. This error message is intended. But since `text` is the default for `format`, `nanobot get table -s page` also results in the above error message.

At some point, we should specify valid default configurations depending on the user's input. I don't think it's a problem for this branch but it's worth another issue, I think.

**Comment by jamesaoverton** [comment]
Thanks @ckindermann!

Yes, these are the combinations of shape and format that I want to support for now. Eventually we will support more, but not every possible combination.

**Pull request merged**
