### PR TITLE
Build and test

### LINKED ISSUE #8: Add GitHub Action to test and compile binaries
It would be nice to attach binaries for at least Linux to the GitHub Action results, but I'm still not sure the best way to do this.

As I said in #7, I'm starting to think that a plain GitHub Action calling a `make test` is better than a fancy custom GitHub Action. One benefit is that you can run `make` locally, while it's hard to replicate a GitHub Action environment. Debugging GitHub Actions is particularly painful.

### PR DESCRIPTION
**Pull request by ckindermann**
This GitHub Action

1. builds a `nanobot` binary,
2. uploads this binary as an artifact,
3. and runs a test by comparing the output of `nanobot init` with the contents of `tests/init.txt`. 

Setting up tests in this way doesn't seem too painful.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Do you think it make sense to fold this into the same GitHub Action as #10?

**Comment by ckindermann** [comment]
Yes. We'd only need to add the `cargo fmt` action here because `cargo check` is part of `cargo build`.

**Comment by jamesaoverton** [comment]
As discussed on the call, this is what I asked for, but now I'd like to make better use of `make`. I'll update the issue with my new thoughts when I get a minute.

**Review by jamesaoverton — CHANGES_REQUESTED** [review]
After thinking about it for a bit, I would like to replace most of the GitHub Action steps with `make` tasks that can also be run locally:

- `make deps` check for Ubuntu (`20.04`), then `apt-get install rust cargo` any required dependencies
- `make format` run `cargo` format checks
- `make build` build binaries
- `make test` run `cargo test` and `tesh` integration tests on binaries

Specialized GitHub Action steps will still be required for checkout and uploading binaries, but everything that is not specific to GitHub Actions should run through `make`.

**Comment by lmcmicu** [comment]
> After thinking about it for a bit, I would like to replace most of the GitHub Action steps with `make` tasks that can also be run locally:
> 
>     * `make deps` check for Ubuntu, then `apt-get install rust cargo` any required dependencies
> 
>     * `make format` run `cargo` format checks
> 
>     * `make build` build binaries
> 
>     * `make test` run integration tests on binaries
> 
> 
> Specialized GitHub Action steps will still be required for checkout and uploading binaries, but everything that is not specific to GitHub Actions should run through `make`.

I don't know if this is helpful (maybe not at all), but there are Makefile targets that do similar things to some of the things that James is asking for here in [valve.py's Makefile](https://github.com/ontodev/valve.py/blob/37fff90e78c803181a058c259ea5faada3faec47/Makefile#L77)

**Pull request merged**
