### PR TITLE
Basic JSON Encoding of Term Trees

### LINKED ISSUE #31: Add ontology term(s) tree JSON shape
TODO: Finish writing this issue.

Building on XXXX, this issue is about the hierarchy. OLS does the best job of displaying ontology trees, so we should copy them. UBERON 'lung' is a good example of one of the most complex trees we would expect to have: <https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0002048>.

The hierarchy is a tree view that locates the subject in the ontology, and should handle: classes, properties, individuals, and selected existential restrictions such as 'has part'; it should include all ancestors, children, and whether the child has children.

The JSON for the hierarchy should be a set of nested objects, starting from the root terms. We also need labels for all the terms.

Although ontology browsers usually focus on a single subject at a time, it would be good to think about how we would represent more than one subject. We should also think about representing subjects in graphs more generally, but ontologies with their subclass hierarchies are the priority.

### LINKED ISSUE #36: Implement queries for top-level nodes
Our ontology browser needs to be able to list all the top-level owl:Class, owl:ObjectProperty, and owl:DatatypeProperty nodes. This is how it's implemented in Gadget: [gadget/tree.py](https://github.com/ontodev/gadget/blob/6cadab1ab2d946a055f84c18a87dc107aeb8aa66/gadget/tree.py#L131). It can be slow for large ontologies, so suggestions are welcome.

### LINKED ISSUE #37: Consider implementing preferred root classes
OLS supports an optional "preferred root" view that uses <http://purl.obolibrary.org/obo/IAO_0000700> 'has ontology root term' to truncate the tree. There can be more than one root. This makes it easier for domain experts to start browsing, without digging through the top layers of upper-level ontology terms.

### PR DESCRIPTION
**Pull request by ckindermann**
Closes #31 

The current JSON view for a given term includes

- all ancestors
- existential restrictions using 'has part'

Missing features are

1. inclusion of children
2. labels for all the terms
3. representation of more than one subject

I am not sure how we should handle information about child classes. It's obviously easy to simply add all child classes of a term to its JSON encoding. But OLS seems to add information about child classes on demand, e.g., in response to user input. Navigating down in the tree view often takes a second or two before child classes are displayed. It's quite fast and works well in practice I suppose! All I'm saying is that it's not instant - and in a few cases, it feels like two seconds rather than one.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
OLS uses a fair bit of client-side JavaScript, but we want to be able to render static pages for trees. So we need to include children, and we need to know whether each child has any children.

**Comment by ckindermann** [comment]
We now have four different data formats for term trees:

1. Simple JSON (using CURIEs or labels)
2. Simple Markdown
3. Rich JSON
4. Rich HTML (encoded as JSON Hiccup)

These formats are used for different purposes. I will explain these purposes and give examples using [gill](https://www.ebi.ac.uk/ols/ontologies/zfa/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FZFA_0000354) in OLS.

# Simple Format 

Formats 1 & 2 follow the same ('simple') abstract structure: a map of entities to their respective `subclasses` and `part-of` relations. An entity is encoded as a string. A `subclass` or `part-of` relationship is encoded via a nested map, i.e., `"zebrafish anatomical entity": { "anatomical structure": {...}  }` means that `anatomical structure` is a `subclass` of `zebrafish anatomical entity`. In the case of a `part-or` relationship, an entity's key includes the prefix `partOf`, e.g., `"whole organism": { "partOf compound organ": {  ... } }`. The entire tree for gill in OLS looks like this:

<details>
  <summary>
    Simple JSON Example
  </summary>

```
{
  "zebrafish anatomical entity": {
    "anatomical structure": {
      "whole organism": {
        "partOf compound organ": {
          "gill": "owl:Nothing"
        },
        "partOf anatomical system": {
          "respiratory system": {
            "partOf gill": "owl:Nothing"
          }
        }
      },
      "compound organ": {
        "gill": "owl:Nothing"
      },
      "anatomical group": {
        "anatomical system": {
          "respiratory system": {
            "partOf gill": "owl:Nothing"
          }
        }
      }
    }
  }
}
```
</details>

Writing this, I notice that "owl:Nothing" is used as a string in the place of a value. To keep the format consistent, this should also be a map. In any case, this format is used to validate the `subclass` and `part-of` relations extracted from an LDTab database with OLS. The test pipeline looks like follows: 

1. Given a term, e.g., gill,
2. get term tree information from OLS in [JSON](https://www.ebi.ac.uk/ols/api/ontologies/zfa/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FZFA_0000354/jstree?viewMode=All&lang=en&siblings=false) 
3. transform information from 2. into the simple format shown above
4. construct the simple term tree using an LDTab database
5. compare both term trees (encoded as JSON)

Coming back to the implemented formats, the Markdown encoding looks as follows:

<details>
  <summary>
    Markdown Example
  </summary>

- zebrafish anatomical entity
	- anatomical structure
		- anatomical group
			- anatomical system
				- respiratory system
					- partOf gill
						- owl:Nothing
		- compound organ
			- gill
				- owl:Nothing
		- whole organism
			- partOf compound organ
				- gill
					- owl:Nothing
			- partOf anatomical system
				- respiratory system
					- partOf gill
						- owl:Nothing
</details>

# Rich Format

The 'rich' format encodes an entity as a JSON object with information about its CURIE, label, and children. Children are entities that are related to an entity via `subclass` and `part-of` relationships. Each JSON object also contains information about the relationship to its parent. In addition to information that is encoded in the simple format, the rich format also includes a branch for children and grand children in the first occurrence of an entity (note that the tree representation is lexicographically ordered by labels).

<details>
  <summary>
    Rich Structure Example
  </summary>

 ```
[
  {
    "curie": "obo:ZFA_0100000",
    "label": "zebrafish anatomical entity",
    "property": "rdfs:subClassOf",
    "children": [
      {
        "curie": "obo:ZFA_0000037",
        "label": "anatomical structure",
        "property": "rdfs:subClassOf",
        "children": [
          {
            "curie": "obo:ZFA_0001512",
            "label": "anatomical group",
            "property": "rdfs:subClassOf",
            "children": [
              {
                "curie": "obo:ZFA_0001439",
                "label": "anatomical system",
                "property": "rdfs:subClassOf",
                "children": [
                  {
                    "curie": "obo:ZFA_0000272",
                    "label": "respiratory system",
                    "property": "rdfs:subClassOf",
                    "children": [
                      {
                        "curie": "obo:ZFA_0000354",
                        "label": "gill",
                        "property": "obo:BFO_0000050",
                        "children": [
                          {
                            "curie": "obo:ZFA_0000716",
                            "label": "afferent branchial artery",
                            "property": "obo:BFO_0000050",
                            "children": [
                              {
                                "curie": "obo:ZFA_0005012",
                                "label": "afferent filamental artery",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0005013",
                                "label": "concurrent branch afferent branchial artery",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0005014",
                                "label": "recurrent branch afferent branchial artery",
                                "property": "obo:BFO_0000050",
                                "children": []
                              }
                            ]
                          },
                          {
                            "curie": "obo:ZFA_0000319",
                            "label": "branchiostegal membrane",
                            "property": "obo:BFO_0000050",
                            "children": []
                          },
                          {
                            "curie": "obo:ZFA_0000202",
                            "label": "efferent branchial artery",
                            "property": "obo:BFO_0000050",
                            "children": [
                              {
                                "curie": "obo:ZFA_0005018",
                                "label": "efferent filamental artery",
                                "property": "obo:BFO_0000050",
                                "children": []
                              }
                            ]
                          },
                          {
                            "curie": "obo:ZFA_0000667",
                            "label": "gill filament",
                            "property": "obo:BFO_0000050",
                            "children": [
                              {
                                "curie": "obo:ZFA_0000666",
                                "label": "filamental artery",
                                "property": "obo:BFO_0000050",
                                "children": []
                              }
                            ]
                          },
                          {
                            "curie": "obo:ZFA_0005324",
                            "label": "gill ionocyte",
                            "property": "obo:BFO_0000050",
                            "children": []
                          },
                          {
                            "curie": "obo:ZFA_0000211",
                            "label": "gill lamella",
                            "property": "obo:BFO_0000050",
                            "children": [
                              {
                                "curie": "obo:ZFA_0005015",
                                "label": "afferent lamellar arteriole",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0005019",
                                "label": "efferent lamellar arteriole",
                                "property": "obo:BFO_0000050",
                                "children": []
                              }
                            ]
                          },
                          {
                            "curie": "obo:ZFA_0001613",
                            "label": "pharyngeal arch 3-7",
                            "property": "obo:BFO_0000050",
                            "children": [
                              {
                                "curie": "obo:ZFA_0000172",
                                "label": "branchial muscle",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0005390",
                                "label": "gill ray",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0001606",
                                "label": "pharyngeal arch 3",
                                "property": "rdfs:subClassOf",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0000095",
                                "label": "pharyngeal arch 3-7 skeleton",
                                "property": "obo:BFO_0000050",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0001607",
                                "label": "pharyngeal arch 4",
                                "property": "rdfs:subClassOf",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0001608",
                                "label": "pharyngeal arch 5",
                                "property": "rdfs:subClassOf",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0001609",
                                "label": "pharyngeal arch 6",
                                "property": "rdfs:subClassOf",
                                "children": []
                              },
                              {
                                "curie": "obo:ZFA_0001610",
                                "label": "pharyngeal arch 7",
                                "property": "rdfs:subClassOf",
                                "children": []
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          },
          {
            "curie": "obo:ZFA_0000496",
            "label": "compound organ",
            "property": "rdfs:subClassOf",
            "children": [
              {
                "curie": "obo:ZFA_0000354",
                "label": "gill",
                "property": "rdfs:subClassOf",
                "children": []
              }
            ]
          },
          {
            "curie": "obo:ZFA_0001094",
            "label": "whole organism",
            "property": "rdfs:subClassOf",
            "children": [
              {
                "curie": "obo:ZFA_0001439",
                "label": "anatomical system",
                "property": "obo:BFO_0000050",
                "children": [
                  {
                    "curie": "obo:ZFA_0000272",
                    "label": "respiratory system",
                    "property": "rdfs:subClassOf",
                    "children": [
                      {
                        "curie": "obo:ZFA_0000354",
                        "label": "gill",
                        "property": "obo:BFO_0000050",
                        "children": []
                      }
                    ]
                  }
                ]
              },
              {
                "curie": "obo:ZFA_0000496",
                "label": "compound organ",
                "property": "obo:BFO_0000050",
                "children": [
                  {
                    "curie": "obo:ZFA_0000354",
                    "label": "gill",
                    "property": "rdfs:subClassOf",
                    "children": []
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
]
```
</details>

This JSON structure can be transformed into a JSON hiccup representation:

<details>
  <summary>
    Rich JSON Hiccup Example
  </summary>

```
["ul",["li","Ontology"],["li",["a",{"resource":"owl:Class"},"owl:Class"],["ul",["li",["a",{"resource":"obo:ZFA_0100000"},"zebrafish anatomical entity"],["ul",["li",["a",{"resource":"obo:ZFA_0000037","about":"obo:ZFA_0100000","rev":"rdfs:subClassOf"},"anatomical structure"],["ul",["li",["a",{"resource":"obo:ZFA_0001512","about":"obo:ZFA_0000037","rev":"rdfs:subClassOf"},"anatomical group"],["ul",["li",["a",{"resource":"obo:ZFA_0001439","about":"obo:ZFA_0001512","rev":"rdfs:subClassOf"},"anatomical system"],["ul",["li",["a",{"resource":"obo:ZFA_0000272","about":"obo:ZFA_0001439","rev":"rdfs:subClassOf"},"respiratory system"],["ul",["li",["a",{"resource":"obo:ZFA_0000354","about":"obo:ZFA_0000272","rev":"obo:BFO_0000050"},"gill"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0000716","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"afferent branchial artery"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0005012","about":"obo:ZFA_0000716","rev":"obo:BFO_0000050"},"afferent filamental artery"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0005013","about":"obo:ZFA_0000716","rev":"obo:BFO_0000050"},"concurrent branch afferent branchial artery"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0005014","about":"obo:ZFA_0000716","rev":"obo:BFO_0000050"},"recurrent branch afferent branchial artery"],["ul",{"id":"children"}]]]],["li",["a",{"resource":"obo:ZFA_0000319","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"branchiostegal membrane"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0000202","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"efferent branchial artery"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0005018","about":"obo:ZFA_0000202","rev":"obo:BFO_0000050"},"efferent filamental artery"],["ul",{"id":"children"}]]]],["li",["a",{"resource":"obo:ZFA_0000667","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"gill filament"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0000666","about":"obo:ZFA_0000667","rev":"obo:BFO_0000050"},"filamental artery"],["ul",{"id":"children"}]]]],["li",["a",{"resource":"obo:ZFA_0005324","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"gill ionocyte"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0000211","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"gill lamella"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0005015","about":"obo:ZFA_0000211","rev":"obo:BFO_0000050"},"afferent lamellar arteriole"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0005019","about":"obo:ZFA_0000211","rev":"obo:BFO_0000050"},"efferent lamellar arteriole"],["ul",{"id":"children"}]]]],["li",["a",{"resource":"obo:ZFA_0001613","about":"obo:ZFA_0000354","rev":"obo:BFO_0000050"},"pharyngeal arch 3-7"],["ul",{"id":"children"},["li",["a",{"resource":"obo:ZFA_0000172","about":"obo:ZFA_0001613","rev":"obo:BFO_0000050"},"branchial muscle"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0005390","about":"obo:ZFA_0001613","rev":"obo:BFO_0000050"},"gill ray"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0001606","about":"obo:ZFA_0001613","rev":"rdfs:subClassOf"},"pharyngeal arch 3"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0000095","about":"obo:ZFA_0001613","rev":"obo:BFO_0000050"},"pharyngeal arch 3-7 skeleton"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0001607","about":"obo:ZFA_0001613","rev":"rdfs:subClassOf"},"pharyngeal arch 4"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0001608","about":"obo:ZFA_0001613","rev":"rdfs:subClassOf"},"pharyngeal arch 5"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0001609","about":"obo:ZFA_0001613","rev":"rdfs:subClassOf"},"pharyngeal arch 6"],["ul",{"id":"children"}]],["li",["a",{"resource":"obo:ZFA_0001610","about":"obo:ZFA_0001613","rev":"rdfs:subClassOf"},"pharyngeal arch 7"],["ul",{"id":"children"}]]]]]]]]]]]],["li",["a",{"resource":"obo:ZFA_0000496","about":"obo:ZFA_0000037","rev":"rdfs:subClassOf"},"compound organ"],["ul",["li",["a",{"resource":"obo:ZFA_0000354","about":"obo:ZFA_0000496","rev":"rdfs:subClassOf"},"gill"],["ul",{"id":"children"}]]]],["li",["a",{"resource":"obo:ZFA_0001094","about":"obo:ZFA_0000037","rev":"rdfs:subClassOf"},"whole organism"],["ul",["li",["a",{"resource":"obo:ZFA_0001439","about":"obo:ZFA_0001094","rev":"obo:BFO_0000050"},"anatomical system"],["ul",["li",["a",{"resource":"obo:ZFA_0000272","about":"obo:ZFA_0001439","rev":"rdfs:subClassOf"},"respiratory system"],["ul",["li",["a",{"resource":"obo:ZFA_0000354","about":"obo:ZFA_0000272","rev":"obo:BFO_0000050"},"gill"],["ul",{"id":"children"}]]]]]],["li",["a",{"resource":"obo:ZFA_0000496","about":"obo:ZFA_0001094","rev":"obo:BFO_0000050"},"compound organ"],["ul",["li",["a",{"resource":"obo:ZFA_0000354","about":"obo:ZFA_0000496","rev":"rdfs:subClassOf"},"gill"],["ul",{"id":"children"}]]]]]]]]]]]]]
```
</details>

# TODOs

1. Test harness: we have code to compare term trees built using information from OLS, on the one hand, and information from LDTab databases on the other hand. At the moment, I've only run tests on a bunch of (random) examples. I'm not sure this is the best way to go about it (this code is not in this pull request).
2. Error handling: The code for building the different term tree formats only propagates `sqlx::Errors` stemming from queries to an LDTab database. So, there are many `unwrap`s on JSON values that depend on correctly formatted LDTab values and term tree values. I'm not sure what the best strategy for error handling in this scenario is but I think it would make sense to have a dedicated validation mechanism for both LDTab and the term trees (we already talked about this some time ago. We put this on hold because of potential changes to either format).
3. Documentation: top-level functions should include some executable doc string code examples/tests (this should be done as soon as we know that the formats won't change too much).
4. Refactoring: I am not sure whether we want to maintain the code for both the simple and the rich format in one file. It seems to me that the simple format is only used for testing and validation purposes. I would expect only the rich format to be relevant for practical purposes.

**Comment by ckindermann** [comment]
Error handling should be revisited at some point because we are currently only propagating `sqlx::Error`. For functions that depend on correctly formatted LDTab values or correctly formatted JSON term trees, there is no proper error handling. In the hiccup encoding for example, we are currently returning Values directly and use `json!("ERROR")` to indicate errrors.

**Comment by ckindermann** [comment]
The module `src/test` currently depends on OLS version 3. The validation tests will need to be updated wrt. OLS version 4 as soon as hierarchical relationships such as 'part-of' are supported again.

**Comment by ckindermann** [comment]
The `term_tree.rs` module is getting somewhat large and implements a bunch of things that should be handled separately. Here is a summary of what I think should be pulled apart:

- Construction of term trees (we essentially maintain trees internally via HashMaps from ancestors to children)
- Construction of term trees for top-level entities (note that this is different from *ancestor* term trees)
- JSON encoding of term trees
- Hiccup encoding of term trees
- HTML display of information (here I mean functions such as `get_hiccup_term_tree` that essentially just arrange different HTML/hiccup elements)

Maintaining these things separately should make some dependencies more obvious. For example, the Hiccup encoding depends on the JSON encoding -- meaning that term trees (maintained internally with HashMaps) first need to be turned into the JSON format, which can then be turned into a Hiccup-style list. (BTW: This dependency is of course not strictly necessary and we could implement a Hiccup encoding based on HashMaps. But that's beside my point.)

**Pull request merged**
